version: "3"


services:
  mongodb:
    image: mongo:latest
    container_name: crud-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: blog

    ports:
      - "27017:27017"

    healthcheck:
      test: ['CMD', "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s

  curdapp:
    build:
      context: .
      dockerfile: dockerfile

    container_name: crud-app
    ports:
    - "8000:8000"

    depends_on:
      mongodb:
        condition: service_healthy
      
      