version: "3"


services:
  mongodb:
    image: mongo:latest
    container_name: crud-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: blog

    ports:
      - "27017:27017"


  curdapp:
    build:
      context: .
      dockerfile: DockerFile

    container_name: crud-app
    ports:
    - "8000:8000"

    depends_on:
      - mongodb
      
      