FROM python:3.9-slim

# Update the system and install required packages
RUN apt-get update \
    && apt-get install -y python3-dev build-essential pkg-config \
    && rm -rf /var/lib/apt/lists/*

 WORKDIR /app
# Copy requirements.txt to the container
COPY requirements.txt /app

# Install Python dependencies from requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the application code to the container
COPY . /app


# Expose the application port
EXPOSE 8000

# Start the application with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
